
package org.soap2;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservationService", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<org.soap2.ReserveFurnitureResponse>
     */
    @WebMethod(operationName = "ReserveFurniture")
    @RequestWrapper(localName = "ReserveFurniture", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "org.soap2.ReserveFurniture")
    @ResponseWrapper(localName = "ReserveFurnitureResponse", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "org.soap2.ReserveFurnitureResponse")
    public Response<ReserveFurnitureResponse> reserveFurnitureAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ReserveFurniture")
    @RequestWrapper(localName = "ReserveFurniture", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "org.soap2.ReserveFurniture")
    @ResponseWrapper(localName = "ReserveFurnitureResponse", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "org.soap2.ReserveFurnitureResponse")
    public Future<?> reserveFurnitureAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<ReserveFurnitureResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.soap2.UserReserve
     */
    @WebMethod(operationName = "ReserveFurniture")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ReserveFurniture", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "org.soap2.ReserveFurniture")
    @ResponseWrapper(localName = "ReserveFurnitureResponse", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", className = "org.soap2.ReserveFurnitureResponse")
    @Action(input = "http://asu.dgtu.donetsk.ua/ex/students/ReservationService/ReserveFurnitureRequest", output = "http://asu.dgtu.donetsk.ua/ex/students/ReservationService/ReserveFurnitureResponse")
    public UserReserve reserveFurniture(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
